trigger:
  - master

variables:
  appName: SYNONYMS

stages:

  - stage: Static Code Analysis
    jobs: 
      - template: pipeline-templates\static-code-analysis.yml

  - stage: Build
    jobs:
      - template: pipeline-templates\build-and-publish-artifacts.yml

  - stage: Release_RG_RUN
    dependsOn: Build
    condition: succeeded()
    jobs:
      - template: pipeline-templates\release-rg-env.yml
        parameters:
          env: "RUN"
          app: ${{ variables.appName }}
